apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.deploy.name }}
  labels:
    name:  {{ .Values.deploy.name }}
spec:
  type: "{{.Values.service.type}}"
  ports:
  - name: http
    port: 80
    targetPort: {{.Values.service.port}}
  selector:
    app: {{ .Values.deploy.name }}